config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
]

home/urls.py
from django.urls import path
from home import views
app_name = 'home'

urlpatterns = [
    path('', views.IndexList.as_view(), name='index'),
    path('category/<int:id>/', views.ProductList.as_view(), name='list'),
    path('<int:pk>/', views.ProductDetail.as_view(), name='detail'),
    path('cart/', views.ShoppingCart.as_view(), name='cart'),
    path('order/', views.Order.as_view(), name='order'),
]

home/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=35)

    def __str__(self):
        return f"{self.name}"


class Unit(models.Model):
    name = models.CharField(max_length=32)

    def __str__(self):
        return f"{self.name}"

class Product(models.Model):

    category_id = models.ForeignKey(Category, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    visible = models.BooleanField(default=False)
    storage = models.IntegerField()
    image = models.URLField(max_length=255, null=False, blank=True)
    name = models.CharField(max_length=55)
    ean = models.CharField(max_length=13, null=False, blank=True, db_index=True)
    description = models.TextField(max_length=10000, null=True, blank=True)
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE)
    time_create = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return f"{self.name}"

class ShipingAdress(models.Model):

    first_name = models.CharField(max_length=64, null=True)
    last_name = models.CharField(max_length=64, null=True)
    phone_number = models.CharField(max_length=12, null=True, blank=True)
    post_code = models.CharField(max_length=6)
    city = models.CharField(max_length=64)
    adress = models.CharField(max_length=255)

class Orders(models.Model):

    ORDER_STATUS = [
        ('completed', 'Wysłano'),
        ('in_progress', 'W realizacji'),
        ('order_accept', 'Przyjęto zamówienie')
    ]
    status = models.CharField(max_length=18, choices=ORDER_STATUS)
    product_id = models.ManyToManyField(Product, through='Order_item')
    email = models.EmailField(max_length=128)
    phone_number = models.CharField(max_length=12, null=True, blank=True)
    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    post_code = models.CharField(max_length=6)
    city = models.CharField(max_length=64)
    adress = models.CharField(max_length=255)
    country = models.CharField(max_length=32)
    description = models.TextField(max_length=2000, null=True, blank=True)
    time_create = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class Order_item(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    orders = models.ForeignKey(Orders, on_delete=models.CASCADE)
    value = models.IntegerField()

    def __str__(self):
        return f"{self.orders} {self.product} Ilość: {self.value}"

home/forms.py
from django import forms

from django.forms.widgets import NumberInput

class ShoppingCartOrderForm(forms.Form):
    first_name = forms.CharField(label='Imię', min_length=1, max_length=64, widget=forms.TextInput(attrs={'class':'form-control'}))
    last_name = forms.CharField(label='Nazwisko', min_length=1, max_length=64, widget=forms.TextInput(attrs={'class':'form-control'}))
    email = forms.EmailField(label='e-mail', min_length=3, max_length=128, widget=forms.TextInput(attrs={'class':'form-control'}))
    phone_number = forms.CharField(label='Nr telefonu', max_length=12, required=False, widget=forms.TextInput(attrs={'placeholder': 'Pole nie obowiązkowe','class':'form-control'}))
    post_code = forms.CharField(label='Kod pocztowy', min_length=6, max_length=6, widget=forms.TextInput(attrs={'class':'form-control'}))
    adress = forms.CharField(label='Ulica', max_length=255, widget=forms.TextInput(attrs={'class':'form-control'}))
    city = forms.CharField(label='Miasto', max_length=64, widget=forms.TextInput(attrs={'class':'form-control'}))
    country = forms.CharField(label='Kraj', max_length=32, widget=forms.TextInput(attrs={'class':'form-control'}))
    descryption = forms.CharField(label='Komentarz do zamówienia', max_length=2000, required=False, widget=forms.Textarea(attrs={'rows':5, 'placeholder': 'Pole nie obowiązkowe','class':'form-control'}))

home/views.py
import decimal
from django.shortcuts import render
from django.shortcuts import redirect
from home.models import Product
from home.models import Category
from home.models import Orders
from home.models import Order_item
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.shortcuts import get_list_or_404
from django.shortcuts import Http404
from django.views import View
from home.forms import ShoppingCartOrderForm
# Create your views here.

class ShoppingCart(View):

    def _get_session_cart_to_dict(self, request):
        if not request.session.get('cart'):
            request.session['cart'] = {}
        sesion_cart = dict(request.session.get('cart'))
        return sesion_cart

    def _add_cart_item(self, request):
        quantity = request.POST.get('product_quantity')
        id = request.POST.get('id_product')
        sesion_cart = self._get_session_cart_to_dict(request)
        if sesion_cart.get(id):
            quantity = int(quantity) + int(sesion_cart.get(id))
            if Product.objects.only('storage').filter(id=id, storage__lt=quantity):
                return redirect('home:cart')
        sesion_cart[id] = quantity
        request.session['cart'] = sesion_cart
        return redirect('home:cart')

    def _update_cart(self, request):
        quantity = request.POST.get('product_quantity')
        id = request.POST.get('id_product')
        if Product.objects.only('storage').filter(id=id, storage__lt=quantity):
            return redirect('home:cart')
        sesion_card = dict(request.session.get('cart'))
        sesion_card[id] = quantity
        request.session['cart'] = sesion_card
        return redirect('home:cart')

    def _del_cart_item(self, request):
        cart_item_to_del = request.POST.get('id_product')
        session_card = dict(request.session.get('cart'))
        session_card.pop(cart_item_to_del)
        request.session['cart'] = session_card
        return redirect('home:cart')

    def _total_sum(self, cart_product):
        total = decimal.Decimal()
        for cart in cart_product:
            total += cart[2]
        return total

    def _bulid_cart(self, products, sess):
        cart_product = []
        for product in products:
            cart_product.append(
                [
                    product, sess[str(product.pk)],
                    decimal.Decimal(sess[str(product.pk)]) * product.price
                ]
            )
        return cart_product

    def _generate_cart(self, session_cart):
        cart = {}
        id_to_query_sql = list(session_cart)
        products = Product.objects.all().filter(pk__in = id_to_query_sql)
        cart['cart_product'] = self._bulid_cart(products,session_cart)
        cart['total_sum'] = self._total_sum(cart['cart_product'])
        return cart

    def _order(self, request):
        items = dict(request.session.get('cart'))
        form = ShoppingCartOrderForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            order = Orders.objects.create(
                status='order_accept',
                email=data.get('email'),
                first_name=data.get('first_name'),
                last_name=data.get('last_name'),
                post_code=data.get('post_code'),
                phone_number=data.get('phone_number'),
                city=data.get('city'),
                adress=data.get('adress'),
                country=data.get('country'),
                description=data.get('descryption')
            )
            for id, value in items.items():
                Order_item.objects.create(
                    product=Product.objects.all().get(pk=id),
                    orders=order,
                    value=value
                )
            request.session.clear()
            return redirect('home:cart')

        session_cart = self._get_session_cart_to_dict(request)
        cart = self._generate_cart(session_cart)
        how_many_items_in_cart = self.how_many_items_it_is_in_cart(request)
        return render(
            request,
            'home/cart.html'
            , context={
                'menu': Category.objects.only('name'),
                'cart_product': cart['cart_product'],
                'total': cart['total_sum'],
                'form': form,
                'how_many_items_in_cart': how_many_items_in_cart,
            }
        )

    def how_many_items_it_is_in_cart(self, request):
        session_cart = self._get_session_cart_to_dict(request)
        values_cart = [int(i) for i in session_cart.values()]
        sum_items_in_cart = sum(values_cart)
        return sum_items_in_cart

    def post(self, request):
        if request.POST.get('operation') == 'delete_item_cart':
            return self._del_cart_item(request)
        elif request.POST.get('operation') == 'update_item_cart':
            return self._update_cart(request)
        elif request.POST.get('operation') == 'add_to_cart':
            return self._add_cart_item(request)
        elif request.POST.get('operation') == 'order_item':
            return self._order(request)
        else:
            raise Http404()

    def get(self, request):
        session_cart = self._get_session_cart_to_dict(request)
        cart = self._generate_cart(session_cart)
        how_many_items_in_cart = self.how_many_items_it_is_in_cart(request)
        form = ShoppingCartOrderForm()
        return render(
           request,
           'home/cart.html'
           ,context={
               'menu':Category.objects.only('name'),
                'cart_product': cart['cart_product'],
                'total': cart['total_sum'],
                'form':form,
                'how_many_items_in_cart':how_many_items_in_cart,
           }
       )

#Disabled
class Order(View):
    def post(self, request):
        items = dict(request.session.get('cart'))
        form = ShoppingCartOrderForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            print(data)
            order = Orders.objects.create(
                status ='order_accept',
                email = data.get('email'),
                first_name = data.get('first_name'),
                last_name = data.get('last_name'),
                post_code = data.get('post_code'),
                phone_number = data.get('phone_number'),
                city = data.get('city'),
                adress = data.get('adress'),
                country = data.get('country'),
                description = data.get('descryption')
            )
            for id, value in items.items():
                Order_item.objects.create(
                    product = Product.objects.all().get(pk=id),
                    orders = order,
                    value = value
            )
            request.session.clear()
            return render(request,'home/order.html', context = {'menu':Category.objects.only('name')})

    def get(self, request):
        form = ShoppingCartOrderForm()
        return render(request,'home/order.html', context = {'menu':Category.objects.only('name'), 'form':form})


class IndexList(ListView):
    model = Product
    template_name = 'home/index.html'

    def get_queryset(self):
        return Product.objects.only('price', 'image', 'name' ).order_by('?')[:20]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu'] = Category.objects.only('name')
        context['how_many_items_in_cart'] = ShoppingCart().how_many_items_it_is_in_cart(self.request)
        return context

class ProductList(ListView):
    model = Product
    template_name = 'home/product_list.html'
    paginate_by = 2

    def get_queryset(self):
        product_list = get_list_or_404(Product.objects.all().filter(category_id=self.kwargs.get('id')))
        return product_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu'] = Category.objects.only('name')
        context['how_many_items_in_cart'] = ShoppingCart().how_many_items_it_is_in_cart(self.request)
        return context

class ProductDetail(DetailView):
    model = Product
    template_name = 'home/product_detail.html'

    def post(self, request, *args, **kwargs):
        return redirect('home:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu'] = Category.objects.only('name')
        context['how_many_items_in_cart'] = ShoppingCart().how_many_items_it_is_in_cart(self.request)
        return context

    def render_to_response(self, context, **response_kwargs):
        response = super(DetailView, self).render_to_response(context, **response_kwargs)
        return response

home/templates/home/cart.html
{% extends 'home/layout.html' %} {% load static %}
{% block title %}
Coś do wstawienia
{% endblock %}
{% block list %}
<div class="container">
	{% if cart_product %}

	<table class="table">
		<thead>
			<tr>
				<th scope="col"></th>
				<th scope="col">Nazwa</th>
				<th class="tab-full" scope="col">Cena Brutto</th>
				<th scope="col">Ilość</th>
				<th scope="col">Suma</th>
			</tr>
		</thead>
		<tbody>
			{%for cart in cart_product%}
			<tr>
				<td>
					<img src="{{ cart.0.image }}" />
				</td>
				<td><a href=""></a>{{cart.0.name}}</td>
				<td class="tab-full">{{cart.0.price}} zł</td>
				<td>
					<form method="POST" needs-validation action="{% url 'home:cart' %}">
						{% csrf_token %}
						<input
							type="number"
							name="product_quantity"
							value="{{cart.1}}"
							size="4"
							min="1"
							max="{{cart.0.storage}}"
						/>
						<input type="hidden" name="id_product" value="{{cart.0.id}}" />
						<div>
							<button
								class="btn btn-primary"
								type="submit"
								name="operation"
								title="Aktualizuj"
								value="update_item_cart"
							>
								<i class="bi bi-arrow-repeat"></i>
							</button>
							<button
								class="btn btn-danger"
								type="submit"
								name="operation"
								title="Usuń"
								value="delete_item_cart"
							>
								<i class="bi bi-trash3"></i>
							</button>
						</div>
					</form>
				</td>
				<td>{{ cart.2 }} zł</td>
			</tr>
		</tbody>
		{% endfor %}
	</table>

	<p class="total_price">Suma: {{ total }} zł</p>
	<div class="form_order">

		<div class="accordion" id="accordionExample">
			<div class="accordion-item">
			  <h2 class="accordion-header" id="headingOne">
				<button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
				  Formularz z danymi do wysyłki
				</button>
			  </h2>
			  <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
				<div class="accordion-body">


		<form method="POST" action="{% url 'home:cart' %}" class="row g-3 needs-validation">
			{% csrf_token %}

			<div class="col-md-4">
				<label for="{{ form.first_name.id_for_label }}" class="form-label">{{ form.first_name.label }}</label>
				{{ form.first_name }} 
				{% if form.first_name.errors %}
				<div class="is-invalid"></div>
				<div class="invalid-feedback">Podaj swoje Imię</div>
				{% endif %}
			</div>
			<div class="col-md-4">
				<label for="{{ form.last_name.id_for_label }}" class="form-label"
					>{{ form.last_name.label }}</label
				>
				{{ form.last_name }} 
				{% if form.last_name.errors %}
				<div class="is-invalid"></div>
				<div class="invalid-feedback">Podaj swoje Nazwisko</div>
				{%endif%}
			</div>
			<div class="col-md-4">
				<label for="{{ form.email.id_for_label }}" class="form-label"
					>{{ form.email.label }}</label
				>
				{{ form.email }}
				{% if form.email.errors %}
				<div class="is-invalid"></div>
				<div class="invalid-feedback">Niepoprawny adres e-mail</div>
				{% endif %}
			</div>
			<div class="col-md-6">
				<label for="{{ form.city.id_for_label }}" class="form-label"
					>{{ form.city.label }}</label
				>
				{{ form.city }}
				{% if form.city.errors %}
				<div class="is-invalid"></div>
				<div class="invalid-feedback">Podaj swoje miasto</div>
				{% endif %}
			</div>
			<div class="col-md-4">
				<label for="{{ form.post_code.id_for_label }}" class="form-label"
					>{{ form.post_code.label }}</label
				>
				{{ form.post_code }}
				{% if form.post_code.errors %}
				<div class="is-invalid"></div>
				<div class="invalid-feedback">Podaj kod pocztowy</div>
				{% endif %}
			</div>
			<div class="col-md-4">
				<label for="{{ form.adress.id_for_label }}" class="form-label"
					>{{ form.adress.label }}</label
				>
				{{ form.adress }}
				{% if form.adress.errors %}
				<div class="is-invalid"></div>
				<div class="invalid-feedback">Podaj swoją ulicę</div>
				{% endif %}
			</div>
	
			<div class="col-md-4">
				<label for="{{ form.country.id_for_label }}" class="form-label"
					>{{ form.country.label }}</label
				>
				{{ form.country }}
				{% if form.country.errors %}
				<div class="is-invalid"></div>
				<div class="invalid-feedback">Kraj</div>
				{% endif %}
			</div>
	
			<div class="col-md-4">
				<label for="{{ form.phone_number.id_for_label }}" class="form-label"
					>{{ form.phone_number.label }}</label
				>
				{{ form.phone_number }}
				{% if form.phone_number.errors %}
				<div class="is-invalid"></div>
				<div class="invalid-feedback">Niepoprawny nr telefonu</div>
				{% endif %}
			</div>
			<div class="col-md-12">
				<label for="{{ form.descryption.id_for_label }}" class="form-label"
					>{{ form.descryption.label }}</label
				>
				{{ form.descryption }} {{ form.descryption.errors }}
			</div>
	
			<div class="col-12">
				<button class="btn btn-primary" name="operation" value="order_item" type="submit">Zamawiam</button>
			</div>
		</form>

		
	</div>
  </div>
</div>
</div>

	</div>
	<!--
	<div class="col-12">
		<a href="{% url 'home:order' %}"><button class="btn btn-primary" type="button" >Dalej</button></a>
	</div>
	-->
</div>
{% else %} Twój koszyk jest pusty {% endif %} {% endblock %}

home/templates/home/index.html
{% extends 'home/layout.html' %}
{% load static %}

{% block title %}
Strona Główna
{% endblock %}

{% block list %}
<div class="container">
    <div class="row">
{% for question in object_list %}
        <div class="col-12 col-md-6 col-lg-4 col-xxl-3 list">
            <a href="{% url 'home:detail' question.id %}"><img class="image" src="{{ question.image }}"></a>
            <a href="{% url 'home:detail' question.id %}"><p class="product_text">{{ question.name}}</p></a>
            <a href="{% url 'home:detail' question.id %}"><p class="product_text product_price">{{ question.price }} zł</p></a>
            <div class="shoping_cart">{% include "home/shoping_cart_add_form.html" %}</div>
        </div>
{% endfor %}
</div>
</div>
{% endblock %}

home/templates/home/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="pl">
	<head>
		<meta charset="UTF-8" />
		<title>{% block title %}{% endblock %}</title>
		<link
			href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
			rel="stylesheet"
			integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
			crossorigin="anonymous"
		/>
		<link
			rel="stylesheet"
			href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css"
		/>
		<link rel="stylesheet" href="{% static 'home/css/style.css' %}" />
		{% block style %}{% endblock %}
		<meta
			name="viewport"
			content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1"
		/>
	</head>

	<body>
		<script
			src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
			integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
			crossorigin="anonymous"
		></script>

		<div class="container">
			<div class="row">
				<header><h1>LOGO Najleprzy sklep</h1></header>

				<nav class="navbar navbar-expand-lg navbar-light bg-light">
					<div class="container-fluid">
						<button
							class="navbar-toggler"
							type="button"
							data-bs-toggle="collapse"
							data-bs-target="#navbarSupportedContent"
							aria-controls="navbarSupportedContent"
							aria-expanded="false"
							aria-label="Toggle navigation"
						>
							<span class="navbar-toggler-icon"></span>
						</button>
						<div class="collapse navbar-collapse" id="navbarSupportedContent">
							<ul class="navbar-nav me-auto mb-2 mb-lg-0">
								<li class="nav-item">
									<a
										class="nav-link active"
										aria-current="page"
										href="{% url 'home:index' %}"
										><i class="bi bi-house-door"></i
									></a>
								</li>

								<li><hr class="dropdown-divider" /></li>

								{% for item in menu %}
								<li class="nav-item mobile_nav">
									<a
										class="nav-link active"
										aria-current="page"
										href="{% url 'home:list' item.id %}"
										>{{item.name}}</a
									>
								</li>
								{% endfor %}

								<li class="nav-item dropdown full_nav">
									<a
										class="nav-link dropdown-toggle"
										href="#"
										id="navbarDropdown"
										role="button"
										data-bs-toggle="dropdown"
										aria-expanded="false"
									>
										Książki</a
									>
									<ul class="dropdown-menu" aria-labelledby="navbarDropdown">
										{% for item in menu %}
										<li>
											<a
												class="dropdown-item"
												href="{% url 'home:list' item.id %}"
												>{{item.name}}</a
											>
										</li>
										{% endfor %}
									</ul>
								</li>

								<li><hr class="dropdown-divider" /></li>
							</ul>
						</div>
						<a href="{% url 'home:cart' %}">
							<button
								type="button"
								class="btn btn-primary position-relative"
							>
								<i class="bi bi-cart4"></i>
								<span
									class="position-absolute top-100 start-100 translate-middle badge rounded-pill bg-danger"
								>
									{{ how_many_items_in_cart }}
									<span class="visually-hidden">Twój Koszyk</span>
								</span>
							</button>
						</a>
					</div>
				</nav>
				<main>{% block list %}{% endblock %}</main>
				<footer>Stopka</footer>
			</div>
		</div>
	</body>
</html>

home/templates/home/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

home/templates/home/order.html
{% extends 'home/layout.html' %} {% load static %} 
{% block title %} {% endblock %}
{% block style %} {% endblock %}
{% block list %}
<table class="table">
    <thead>
        <tr>
            <th scope="col"></th>
            <th scope="col">Nazwa</th>
            <th class="tab-full" scope="col">Cena Brutto</th>
            <th scope="col">Ilość</th>
            <th scope="col">Suma</th>
        </tr>
    </thead>
    <tbody>
        {%for cart in cart_product%}
        <tr>
            <td>
                <img src="{{ cart.0.image }}" />
            </td>
            <td>{{cart.0.name}}</td>
            <td class="tab-full">{{cart.0.price}} zł</td>
            <td>{{cart.1}}"</td>
            <td>{{ cart.2 }} zł</td>
        </tr>
    </tbody>
    {% endfor %}
</table>


<div class="form_order">
	<form
		method="POST"
		action="{% url 'home:order' %}"
		class="row g-3 was-validated"
	>
		{% csrf_token %}

		<div class="col-md-4">
			<label for="{{ form.first_name.id_for_label }}" class="form-label"
				>{{ form.first_name.label }}</label
			>
			{{ form.first_name }} {{ form.first_name.errors }}
			<div class="valid-feedback">Dobrze</div>
			<div class="invalid-feedback">Podaj swoje Imię</div>
		</div>
		<div class="col-md-4">
			<label for="{{ form.last_name.id_for_label }}" class="form-label"
				>{{ form.last_name.label }}</label
			>
			{{ form.last_name }} {{ form.last_name.errors }}
			<div class="valid-feedback">Dobrze</div>
			<div class="invalid-feedback">Podaj swoje Nazwisko</div>
		</div>
		<div class="col-md-4">
			<label for="{{ form.email.id_for_label }}" class="form-label"
				>{{ form.email.label }}</label
			>
			{{ form.email }} {{ form.email.errors }}
			<div class="valid-feedback">Dobrze</div>
			<div class="invalid-feedback">Podaj swój adres e-mail</div>
		</div>
		<div class="col-md-6">
			<label for="{{ form.city.id_for_label }}" class="form-label"
				>{{ form.city.label }}</label
			>
			{{ form.city }} {{ form.city.errors }}
			<div class="valid-feedback">Dobrze</div>
			<div class="invalid-feedback">Podaj swoje miasto</div>
		</div>
		<div class="col-md-4">
			<label for="{{ form.post_code.id_for_label }}" class="form-label"
				>{{ form.post_code.label }}</label
			>
			{{ form.post_code }} {{ form.post_code.errors }}
			<div class="valid-feedback">Dobrze</div>
			<div class="invalid-feedback">Podaj kod pocztowy</div>
		</div>
		<div class="col-md-4">
			<label for="{{ form.adress.id_for_label }}" class="form-label"
				>{{ form.adress.label }}</label
			>
			{{ form.adress }} {{ form.adress.errors }}
			<div class="valid-feedback">Dobrze</div>
			<div class="invalid-feedback">Podaj swoją ulicę</div>
		</div>

		<div class="col-md-4">
			<label for="{{ form.country.id_for_label }}" class="form-label"
				>{{ form.country.label }}</label
			>
			{{ form.country }} {{ form.country.errors }}
			<div class="valid-feedback">Dobrze</div>
			<div class="invalid-feedback">Kraj</div>
		</div>

		<div class="col-md-4">
			<label for="{{ form.phone_number.id_for_label }}" class="form-label"
				>{{ form.phone_number.label }}</label
			>
			{{ form.phone_number }} {{ form.phone_number.errors }}
			<div class="valid-feedback">Dobrze</div>
			<div class="invalid-feedback">Podaj nr telefonu</div>
		</div>
		<div class="col-md-12">
			<label for="{{ form.descryption.id_for_label }}" class="form-label"
				>{{ form.descryption.label }}</label
			>
			{{ form.descryption }} {{ form.descryption.errors }}
		</div>

		<div class="col-12">
			<button class="btn btn-primary" type="submit">Zamawiam</button>
		</div>
	</form>
</div>

{% endblock %}

home/templates/home/product_list.html
{% extends 'home/layout.html' %}
{% load static %}

{% block title %}
Lista Produktów
{% endblock %}

{% block list %}
{% if not object_list %}
Nie ma takiej strony
{% endif %}
{{ undo }}
<div class="container">
    <div class="row">
{% for question in object_list %}
<div class="col-12 col-md-6 col-lg-4 col-xxl-3 list">
    <a href="{% url 'home:detail' question.id %}"><img class="image" src="{{ question.image }}"></a>
    <a href="{% url 'home:detail' question.id %}"><p class="product_text">{{ question.name}}</p></a>
    <a href="{% url 'home:detail' question.id %}"><p class="product_text product_price">{{ question.price }} zł</p></a>
    <div class="shoping_cart">{% include "home/shoping_cart_add_form.html" %}</div>
</div>
{% endfor %}
</div>
</div>

<nav aria-label="Pagination">
    <ul class="pagination pagination-sm justify-content-center">
        {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1"><span aria-hidden="true">&laquo;</span></a></li>
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Wstecz</a></li>
        {% else %}
        <li class="page-item disabled"><a class="page-link" href="#"> <span aria-hidden="true">&laquo;</span></a></li>
        <li class="page-item disabled"><a class="page-link" href="#">Wstecz</a></li>
        {% endif %}
        <li class="page-item disabled"><span class="page-link page_number">{{ page_obj.number }} z {{ page_obj.paginator.num_pages }}</span></li>
        {% if page_obj.has_next %}
        <li class="page-item "><a class="page-link" href="?page={{ page_obj.next_page_number }}">Dalej</a></li>
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}"><span aria-hidden="true">&raquo;</span></a></li>
      {% else %}
      <li class="page-item disabled"><a class="page-link" href="#">Dalej</a></li>
      <li class="page-item disabled"><a class="page-link" href="#"><span aria-hidden="true">&raquo;</span></a></li>
      {% endif %}
    </ul>
  </nav>
{% endblock %}